### ISSUE TITLE
Form fields unresponsive no effect (uncaught error: Cannot convert string to number)

### ISSUE THREAD

**Issue by RMurray89** [cgkineo/adapt-visua11y#37]
Hi,

I would love to use this but having some issues with it in practice.

# Issue

Each checkbox has to be clicked twice before the checkbox shows as unchecked. However, no effect is had after selecting these.

Additionally selecting any of the colour profiles from drop-down menu has no effect, as well as the readability settings.

On selecting any of these options an uncaught error is shown in the console:

![image](https://user-images.githubusercontent.com/3612643/174999776-b23ecb9c-50cb-4886-ae2b-80a91452b2df.png)

I'm not sure if this is perhaps a conflict elsewhere with other extensions. In the test these are the active extensions;

![image](https://user-images.githubusercontent.com/3612643/175000034-f636fd08-7301-49db-ab09-c13597af03e7.png)

When testing in a project with the vanilla theme and only a text component, the functionality worked as intended.

I've tested with the current master branch, framework 5.19.5 and the authoring tool.

Apologies in advance if this isn't specific enough but I will try and provide more info if required.

Thanks
Ross

**Comment by oliverfoster** [comment]
please turn on sourcemaps so I can see the lines affected.

**Comment by RMurray89** [comment]
Hi Oliver hopefully this helps;

![image](https://user-images.githubusercontent.com/3612643/175016420-9e40eeac-5668-4273-b127-1e3608f41344.png)

![image](https://user-images.githubusercontent.com/3612643/175016542-b1f43482-2ce2-4023-83cf-4ea8d3b9e646.png)

**Comment by oliverfoster** [comment]
I need you to debug this line with a breakpoint https://github.com/cgkineo/adapt-visua11y/blob/7444d29117ce3d3e8f6f89ccc39cf943b9eb946b/js/adapt-visua11y.js#L274

I need the value of the `data` variable.

**Comment by RMurray89** [comment]
I think I've done this correctly..

Data: 
![image](https://user-images.githubusercontent.com/3612643/175045352-22b64f36-b1ce-4511-8739-d3307d2a4484.png)

And an overview of what I done..

![image](https://user-images.githubusercontent.com/3612643/175045071-eb78f03f-1436-4d2a-95d2-feaf5552a14a.png)

**Comment by oliverfoster** [comment]
fixed, thanks

**Comment by RMurray89** [comment]
Thanks! Appreciate it!

I can really see the potential in this.

Question,

When I launch a course and open the extension, should all the checkboxes be checked? Mines loads like this

![image](https://user-images.githubusercontent.com/3612643/175074013-3c11df79-772c-48dc-8bfc-07b3373083ef.png)

It's like all the effects are enabled by default?

I would think the settings should be inactive until enabled by the learner?

Thanks - Let me know if you want this logged as another ticket. Atm it's just a query from me.

**Comment by oliverfoster** [comment]
You'd enabled them before, it's just restoring what you selected.

**Comment by RMurray89** [comment]
Hi Oliver,

When I preview the course in an incognito window I'm still getting the same, unfortunately. I also published to a new location and have the same problem. The course loads with the filters applied.

Could it be related to this?

![image](https://user-images.githubusercontent.com/3612643/175109652-f707facd-5158-4698-9955-e1ebbbc0fc40.png)

**Comment by oliverfoster** [comment]
Will have a look.
